apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo
spec:
  containers:
  - image: docker.io/mongo:4.1.4
    name: mongo-container
    volumeMounts:
    - mountPath: /data
      name: mongo-volume
  volumes:
  - name: mongo-volume
    hostPath:
      # directory location on host
      path: /home/alex/k8s/mongo

