apiVersion: v1
kind: Service
metadata:
  name: "mysql"
  labels:
    app: "mysql-app"
spec:
  ports:
  - port: 3306  # the port that this service should serve on
  selector:   #used to match deployment's label
    app: "mysql-app"
    tier: mysql