apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/alex/data/myapp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pv-claim
  labels:
    app: myapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - image: justware/myapp:1.0
        name: myapp
        env:
        - name: MySQL_HOST
          value: mysql
        - name: MySQL_PASSWORD  #mysql -u root -p
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: Redis_HOST
          value: redis
        - name: HTTP_PORT
          value: "80"
        - name: LOG_LEVEL
          value: "1"    
        ports:
        - containerPort: 80
          name: myapp
        volumeMounts:
        - name: myapp-persistent-storage
          mountPath: /usr/myapp/data
      volumes:
      - name: myapp-persistent-storage
        persistentVolumeClaim:
          claimName: myapp-pv-claim
