apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello 
  labels:
    app: "MultiContainerApp"
spec:
  selector:
    matchLabels:
      app: "MultiContainerApp"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "MultiContainerApp"
    spec:
      containers:
      - image: mysql:5.7.23
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password      
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql 
      - image: alex/flask:1.0
        name: flask
        ports:
        - containerPort: 80 
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /python
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:  
          claimName: mysql-pv-claim 
