apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello 
  labels:
    app: "MultiContainerApp"
spec:
  selector:
    matchLabels:
      app: "MultiContainerApp"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "MultiContainerApp"
    spec:
      containers:
      - image: alex/flask:1.0
        name: flask
        ports:
        - containerPort: 80 
