apiVersion: v1
kind: Service
metadata:
  name: "hello"
  labels:
    app: "MultiContainerApp"
spec:
  ports:
  # the port that this service should serve on
  - 
    name: flask
    port: 80
  -
    name: mysql
    port: 3306
  #label keys and values that must match in order to receive traffic for this service
  selector:
    app: "MultiContainerApp"
