apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis
        image: redis:6.0.1
        env:
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
        resources:
          limits:
            cpu: "0.1"
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:  
          claimName: redis-pv-claim 
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis-config
            path: redis.conf

